### ISSUE TITLE
[BUG] Prevents Start up of servers

### ISSUE THREAD

**Issue by red2blue** [AnonymousHacker1279/ImmersiveWeapons#60]
So.... after 3 hours of debugging 250 mods, your mod prevented world creation in a server instance. 
I did this one by one, disabling mod after mod, and it came down to Immersive Weapons. There is no log indicating why, but there is a crash error I can provide .

Latest Immersive Weapon version
1.18
Modloader 38.0.17

[20:24:49] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Missing referenced custom/removed registry entry for registry ResourceKey[minecraft:root / minecraft:worldgen/biome] named minecraft:overworld
	at com.mojang.serialization.DataResult.lambda$getOrThrow$4(DataResult.java:100) ~[datafixerupper-4.0.26.jar%2329!:?]
	at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[datafixerupper-4.0.26.jar%2329!:?]
	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93) ~[datafixerupper-4.0.26.jar%2329!:?]
	at net.minecraft.server.Main.main(Main.java:175) ~[server-1.18-20211130.085255-srg.jar%23265!:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:46) ~[fmlloader-1.18-38.0.17.jar%2323!:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?]

**Comment by AnonymousHacker1279** [comment]
I'll take a close look at the issue soon. But just from glancing at the log snippet, it seems like it's a worldgen problem. Which is odd, because I thought I had disabled all of it for the 1.18 beta releases (due to issues in the Forge API).

**Comment by AnonymousHacker1279** [comment]
Found the problem. Part of the datapack for working with custom dimensions wasn't fully disabled, and so it would fail since the entries weren't being registered. I'll have a new beta release out soon.

**Comment by AnonymousHacker1279** [comment]
Should be fixed as of the latest 1.18.1-beta3 release. Let me know if anything else breaks.

**Comment by red2blue** [comment]
will try it out now, thank you.
